### ISSUE TITLE
Default Image Selection Fails

### ISSUE THREAD

**Issue by kennschr** [aws-samples/hub-and-spoke-with-inspection-vpc-terraform#8]
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with module.compute["vpc1"].data.aws_ami.amazon_linux,
│   on ../modules/compute/main.tf line 31, in data "aws_ami" "amazon_linux":
│   31: data "aws_ami" "amazon_linux" {
│

**Comment by pablo19sc** [comment]
Fixed with the update Amazon Linux 2023 AMI - both in single and multi-Account examples.
